//! The fleet work job: what one machine asks another to run (#2916).
//!
//! Until 4.0 this was the payload of the Redis work queue (`darkmux:work`),
//! which any node that could write the hub's Redis could fill and any runner
//! would claim. That queue is retired (#2916): a job now travels in one HTTP
//! request, straight to the target machine's work-submission listener, which
//! checks the fleet token and the connecting node before it runs anything
//! (`submission.rs`). The job's SHAPE checks below are unchanged and still run
//! on both sides.

use anyhow::{anyhow, Result};
use serde::{Deserialize, Serialize};

/// One unit of work one machine asks another to run: the body of a
/// work-submission request (`POST /fleet/work`, see `submission.rs`),
/// inside a [`crate::WorkSubmission`] envelope that carries the wire
/// version.
///
/// `#[serde(deny_unknown_fields)]` (PR-C.2): a sender cannot smuggle extra
/// fields that later receiver code might start interpreting. A shape change
/// is a deliberate [`WORK_JOB_SCHEMA_VERSION`] bump plus a struct edit.
///
/// Nothing in a job is trusted for authorization. `published_by_machine` is
/// the sender's own claim, kept for logs; WHO sent the job is answered by
/// the network (the identity provider) and the fleet token, never by a field
/// the sender writes.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct WorkJob {
    /// The machine the sender addressed (its `machine_id`, #2924). The
    /// receiver refuses a job addressed to another name, so a roster entry
    /// pointing at the wrong host fails loudly instead of running the work
    /// on the wrong machine. (It was an advisory hint while the queue let
    /// any runner claim any job; it is now a check.)
    pub target_machine: String,

    /// Role to dispatch against — resolved to a role manifest on the
    /// receiver.
    pub role_id: String,

    /// The operator's dispatch message — handed verbatim to the runtime.
    pub message: String,

    /// Stable session id, generated by the sender, so the flow records the
    /// receiver emits carry the id the sender printed.
    pub session_id: String,

    /// The receiver's profile to run on (`--profile`). `None` = the
    /// receiver resolves it as its own `dispatch` would (the role's
    /// `role_profiles` binding, else `default_profile`). Either way the
    /// RESOLVED profile is what the allow-list scope is checked against,
    /// and what runs.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub profile: Option<String>,

    /// Optional `--workdir`, a path on the RECEIVER. Refused unless the
    /// sender's allow-list entry grants `workspace` (#755), and then only
    /// under the receiver's worktrees base.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workdir: Option<String>,

    /// Optional phase-id binding — same semantics as DispatchOpts.phase_id.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phase_id: Option<String>,

    /// (#703 Slice 4) Docker image the receiver dispatches into. `None` →
    /// the receiver's default runtime image.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,

    /// Timeout (seconds) passed through to the dispatch.
    pub timeout_seconds: u32,

    /// Unix-millis when the sender built the job.
    pub published_at_unix_ms: u64,

    /// The sender's own `machine_id`, as it claims it. Logged only; never
    /// used to decide anything.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub published_by_machine: Option<String>,
}

/// Wire version of a work submission. History: "1"-"4" were the Redis
/// queue's `schema` tag (#590 single stream, #703 `image`, #1426 retired
/// `deliver`/`runtime`). "5" (#2916) is the first direct-submission shape:
/// `target_machine` became required, `profile` was added, and the dead
/// `attempt` / `published_by_orchestrator` fields were removed. The receiver
/// reads the envelope's `schema` BEFORE parsing the job, so a sender on
/// another version gets a reply naming the version, not a field error.
pub const WORK_JOB_SCHEMA_VERSION: &str = "5";

/// Max byte size of a `WorkJob.message`. 256 KiB matches the
/// reasoning-text cap in `dispatch_internal.rs` (#231 / S6). (#246 PR-C.2)
pub(crate) const MAX_WORK_MESSAGE_BYTES: usize = 256 * 1024;

/// Max byte size of `WorkJob.workdir`. (#246 PR-C.2)
pub(crate) const MAX_WORK_WORKDIR_BYTES: usize = 4 * 1024;

/// Max length for identifier fields (`target_machine`, `role_id`,
/// `profile`). (#246 PR-C.2)
pub(crate) const MAX_WORK_IDENTIFIER_LEN: usize = 64;

/// Max allowed `timeout_seconds`. 1 hour bounds how long one sender can
/// hold a receiver's single work slot. (#246 PR-C.3)
pub(crate) const MAX_WORK_TIMEOUT_SECONDS: u32 = 60 * 60;

/// Max byte size of `WorkJob.image`. (#838 PR-C.2)
pub(crate) const MAX_WORK_IMAGE_BYTES: usize = 256;

impl WorkJob {
    /// Validate a job's SHAPE — called by the sender before the request
    /// leaves and by the receiver before anything runs. Charset and size
    /// only; who may run what is `submission.rs`'s job.
    ///
    /// - `target_machine`, `role_id`: `[a-z0-9_-]{1,64}`.
    /// - `profile`: 1..=64 printable ASCII, no whitespace (profile names
    ///   are the operator's own and may carry dots or capitals; the value
    ///   is only ever compared against names, never used as a path).
    /// - `message` ≤ 256 KiB, `workdir` ≤ 4 KiB, `timeout_seconds` in
    ///   1..=3600, `image` a conservative image reference.
    pub fn validate(&self) -> Result<()> {
        validate_machine_name("WorkJob.target_machine", &self.target_machine)?;
        validate_work_identifier("role_id", &self.role_id)?;
        validate_session_id(&self.session_id)?;
        if let Some(p) = &self.phase_id {
            validate_work_identifier("phase_id", p)?;
        }
        if let Some(p) = &self.profile {
            if p.is_empty() || p.len() > MAX_WORK_IDENTIFIER_LEN || !p.chars().all(|c| c.is_ascii_graphic()) {
                return Err(anyhow!(
                    "WorkJob.profile must be 1..={MAX_WORK_IDENTIFIER_LEN} printable ASCII characters \
                     with no spaces: {p:?}"
                ));
            }
        }
        if self.message.len() > MAX_WORK_MESSAGE_BYTES {
            return Err(anyhow!(
                "WorkJob.message exceeds {}-byte cap (was {} bytes)",
                MAX_WORK_MESSAGE_BYTES,
                self.message.len()
            ));
        }
        if let Some(w) = &self.workdir {
            if w.len() > MAX_WORK_WORKDIR_BYTES {
                return Err(anyhow!(
                    "WorkJob.workdir exceeds {}-byte cap (was {} bytes)",
                    MAX_WORK_WORKDIR_BYTES,
                    w.len()
                ));
            }
        }
        if self.timeout_seconds == 0 {
            return Err(anyhow!(
                "WorkJob.timeout_seconds must be non-zero (0 would never complete)"
            ));
        }
        if self.timeout_seconds > MAX_WORK_TIMEOUT_SECONDS {
            return Err(anyhow!(
                "WorkJob.timeout_seconds exceeds {}-second cap (was {})",
                MAX_WORK_TIMEOUT_SECONDS,
                self.timeout_seconds
            ));
        }
        if let Some(img) = &self.image {
            validate_work_image(img)?;
        }
        Ok(())
    }
}



/// Charset+length check for an identifier-shaped field — the canonical
/// validator used both at the queue boundary (`WorkJob::validate`) and
/// at the CLI boundary (`darkmux mission dispatch <mission_id>` etc.,
/// Wave-E.5 #255).
///
/// Allowlist: `[a-z0-9_-]` (ASCII lowercase + digits + underscore +
/// hyphen), length 1..=MAX_WORK_IDENTIFIER_LEN. The full `label`
/// parameter lets callers name the offending field as the operator
/// thinks of it (`"mission_id"`, `"WorkJob.target_machine"`, etc.) so
/// errors are operator-actionable rather than internal-shape-leaky.
pub fn validate_identifier(label: &str, value: &str) -> Result<()> {
    if value.is_empty() {
        return Err(anyhow!("{label} must be non-empty"));
    }
    if value.len() > MAX_WORK_IDENTIFIER_LEN {
        return Err(anyhow!(
            "{label} exceeds {}-char limit (was {} chars): {value:?}",
            MAX_WORK_IDENTIFIER_LEN,
            value.len()
        ));
    }
    let bad = value
        .chars()
        .find(|c| !(c.is_ascii_lowercase() || c.is_ascii_digit() || *c == '-' || *c == '_'));
    if let Some(c) = bad {
        return Err(anyhow!(
            "{label} contains invalid char {c:?} (allowlist [a-z0-9_-]): {value:?}"
        ));
    }
    Ok(())
}

/// (#2916) A machine name (`machine_id`): `[A-Za-z0-9_-]`, 1..=64. Machine
/// names are ASCII case-INSENSITIVE everywhere (`--machine MacBook-Pro`
/// and `--machine macbook-pro` are the same machine; compare with
/// [`same_machine`]); the displayed name keeps its case. Capitals are
/// allowed because a hostname-derived `machine_id` has them.
pub fn validate_machine_name(label: &str, value: &str) -> Result<()> {
    if value.is_empty() || value.len() > MAX_WORK_IDENTIFIER_LEN {
        return Err(anyhow!("{label} must be 1..={MAX_WORK_IDENTIFIER_LEN} characters: {value:?}"));
    }
    if let Some(c) = value.chars().find(|c| !(c.is_ascii_alphanumeric() || *c == '-' || *c == '_')) {
        return Err(anyhow!("{label} contains invalid char {c:?} (allowlist [A-Za-z0-9_-]): {value:?}"));
    }
    // (#2916 re-review C8) The receiver names a submitted run
    // `<sender session>-from-<peer>`; a machine name containing the
    // separator could make two peers' runs collide.
    if value.to_ascii_lowercase().contains(SESSION_PEER_SEPARATOR) {
        return Err(anyhow!("{label} may not contain `{SESSION_PEER_SEPARATOR}`: {value:?}"));
    }
    Ok(())
}

/// The separator in a receiver's session id, `<sender session>-from-<peer>`.
pub const SESSION_PEER_SEPARATOR: &str = "-from-";

/// (#2916 re-review C6) A session id a receiver echoes back: the sender's
/// own id plus `-from-<peer>`, so up to 128 + 6 + 64 characters, same charset.
pub fn validate_reply_session_id(value: &str) -> Result<()> {
    if value.is_empty() || value.len() > MAX_SESSION_ID_LEN + SESSION_PEER_SEPARATOR.len() + MAX_WORK_IDENTIFIER_LEN {
        return Err(anyhow!("a reply session_id is too long"));
    }
    if value.chars().any(|c| !(c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-'))) {
        return Err(anyhow!("a reply session_id carries a character outside [A-Za-z0-9._-]"));
    }
    Ok(())
}

/// (#2916) Whether two machine names name the same machine.
pub fn same_machine(a: &str, b: &str) -> bool {
    a.eq_ignore_ascii_case(b)
}

/// Max length of a submitted `session_id`.
pub(crate) const MAX_SESSION_ID_LEN: usize = 128;

/// (#2916) A submitted session id: `[A-Za-z0-9._-]{1,128}`. It becomes part
/// of file names and flow-record join keys on the receiver.
pub fn validate_session_id(value: &str) -> Result<()> {
    if value.is_empty() || value.len() > MAX_SESSION_ID_LEN {
        return Err(anyhow!("WorkJob.session_id must be 1..={MAX_SESSION_ID_LEN} characters"));
    }
    if let Some(c) = value.chars().find(|c| !(c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-'))) {
        return Err(anyhow!("WorkJob.session_id contains invalid char {c:?} (allowlist [A-Za-z0-9._-])"));
    }
    Ok(())
}

/// Wraps `validate_identifier` with the `"WorkJob.{field}"` label
/// prefix used throughout `WorkJob::validate`. Kept as a thin shim so
/// the existing internal call-sites read tightly.
fn validate_work_identifier(field: &str, value: &str) -> Result<()> {
    validate_identifier(&format!("WorkJob.{field}"), value)
}

/// Validate a Docker image reference at the queue boundary.
/// Rejects empty strings, values starting with `-` (docker-flag injection,
/// #838), and any char outside the conservative image-ref charset
/// `[A-Za-z0-9._/:@-]`. Also enforces a byte-size cap.
///
/// The allowlist covers the full Docker reference grammar:
/// - registry host (`myregistry.io`)
/// - slash-separated path segments (`org/repo`, `a/b/c`)
/// - colon tag (`:latest`, `:v1.2.3`)
/// - at digest (`@sha256:...`)
/// - dots, underscores, hyphens in names
pub fn validate_image_ref(value: &str) -> Result<()> {
    if value.is_empty() {
        return Err(anyhow!("image must be non-empty"));
    }
    if value.len() > MAX_WORK_IMAGE_BYTES {
        return Err(anyhow!(
            "image exceeds {}-byte cap (was {} bytes): {value:?}",
            MAX_WORK_IMAGE_BYTES,
            value.len()
        ));
    }
    if value.starts_with('-') {
        return Err(anyhow!(
            "image must not start with '-' (prevents docker-flag injection, #838): {value:?}"
        ));
    }
    let bad = value
        .chars()
        .find(|c| !(c.is_ascii_alphanumeric() || *c == '.' || *c == '_' || *c == '/' || *c == '-' || *c == ':' || *c == '@'));
    if let Some(c) = bad {
        return Err(anyhow!(
            "image contains invalid char {c:?} (allowlist [A-Za-z0-9._/:@-]): {value:?}"
        ));
    }
    Ok(())
}

/// Wraps `validate_image_ref` with the `"WorkJob.image"` label prefix.
fn validate_work_image(value: &str) -> Result<()> {
    validate_image_ref(value)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Build a minimal valid WorkJob with all optional fields None.
    fn make_valid_job() -> WorkJob {
        WorkJob {
            target_machine: "studio".to_string(),
            role_id: "test-role".to_string(),
            message: "hello".to_string(),
            session_id: "sess-1".to_string(),
            profile: None,
            workdir: None,
            phase_id: None,
            image: None,
            timeout_seconds: 60,
            published_at_unix_ms: 1_700_000_000_000,
            published_by_machine: None,
        }
    }

    /// (#2916) `target_machine` is required and checked like every
    /// identifier; `profile` allows the operator's own spellings but no
    /// whitespace or control characters.
    #[test]
    fn validate_checks_target_machine_and_profile() {
        let mut job = make_valid_job();
        job.target_machine = "MacBook-Pro".into();
        assert!(job.validate().is_ok(), "machine names may carry capitals (#2916)");
        job.target_machine = "studio.lan".into();
        assert!(job.validate().unwrap_err().to_string().contains("target_machine"));
        assert!(same_machine("MacBook-Pro", "macbook-pro"));
        assert!(!same_machine("macbook-pro", "macbook-pr0"));
        let mut job = make_valid_job();
        job.profile = Some("Coder.Studio-v2".into());
        assert!(job.validate().is_ok());
        for bad in ["", "has space", "tab\t", "x".repeat(65).as_str()] {
            job.profile = Some(bad.to_string());
            assert!(job.validate().unwrap_err().to_string().contains("profile"), "{bad:?}");
        }
    }

    /// (#2916 re-review C4/C6/C8) phase ids are identifiers; machine names
    /// may not contain the session separator; echoed session ids are bounded.
    #[test]
    fn phase_ids_separator_and_reply_ids_are_checked() {
        let mut job = make_valid_job();
        job.phase_id = Some("../x".into());
        assert!(job.validate().unwrap_err().to_string().contains("phase_id"));
        job.phase_id = Some("phase-1".into());
        assert!(job.validate().is_ok());
        assert!(validate_machine_name("m", "laptop-from-home").is_err());
        assert!(validate_machine_name("m", "laptop").is_ok());
        assert!(validate_reply_session_id(&format!("{}-from-{}", "a".repeat(128), "b".repeat(64))).is_ok());
        assert!(validate_reply_session_id("x\u{1b}]0;t").is_err());
        assert!(validate_reply_session_id(&"a".repeat(199)).is_err());
    }

    /// (#2916) A session id is a join key and part of file names on the
    /// receiver: a restricted charset and length.
    #[test]
    fn validate_checks_the_session_id() {
        let mut job = make_valid_job();
        for good in ["radio-host-1790000000-0", "a.b_c-D"] {
            job.session_id = good.into();
            assert!(job.validate().is_ok(), "{good}");
        }
        for bad in ["", "../x", "a b", "a/b", "x\u{1b}[2J", &"a".repeat(129)] {
            job.session_id = bad.to_string();
            assert!(job.validate().unwrap_err().to_string().contains("session_id"), "{bad:?}");
        }
    }

    /// (#2916) The v5 wire shape refuses the fields v4 carried.
    #[test]
    fn v4_only_fields_are_refused() {
        let v = serde_json::to_value(make_valid_job()).unwrap();
        for extra in ["attempt", "published_by_orchestrator"] {
            let mut obj = v.as_object().unwrap().clone();
            obj.insert(extra.into(), serde_json::json!(1));
            let err = serde_json::from_value::<WorkJob>(serde_json::Value::Object(obj)).unwrap_err();
            assert!(err.to_string().contains(extra), "{err}");
        }
    }

    // ---- validate_identifier tests ----

    #[test]
    fn validate_identifier_positive() {
        // lowercase + digits + underscore + hyphen
        assert!(validate_identifier("field", "abc-123_xyz").is_ok());
    }

    #[test]
    fn validate_identifier_empty() {
        let err = validate_identifier("field", "").unwrap_err();
        assert!(err.to_string().contains("must be non-empty"));
    }

    #[test]
    fn validate_identifier_over_length() {
        let long = "a".repeat(MAX_WORK_IDENTIFIER_LEN + 1);
        let err = validate_identifier("field", &long).unwrap_err();
        assert!(err.to_string().contains("exceeds"));
    }

    #[test]
    fn validate_identifier_dot() {
        let err = validate_identifier("field", "a.b").unwrap_err();
        assert!(err.to_string().contains("invalid char"));
    }

    #[test]
    fn validate_identifier_slash() {
        let err = validate_identifier("field", "a/b").unwrap_err();
        assert!(err.to_string().contains("invalid char"));
    }

    #[test]
    fn validate_identifier_double_dot() {
        let err = validate_identifier("field", "..").unwrap_err();
        assert!(err.to_string().contains("invalid char"));
    }

    #[test]
    fn validate_identifier_space() {
        let err = validate_identifier("field", "a b").unwrap_err();
        assert!(err.to_string().contains("invalid char"));
    }

    #[test]
    fn validate_identifier_uppercase() {
        let err = validate_identifier("field", "Abc").unwrap_err();
        assert!(err.to_string().contains("invalid char"));
    }

    #[test]
    fn validate_identifier_embedded_null() {
        let err = validate_identifier("field", "a\0b").unwrap_err();
        assert!(err.to_string().contains("invalid char"));
    }

    // ---- validate_image_ref tests ----

    #[test]
    fn validate_image_ref_valid() {
        // A typical registry/path:tag reference
        assert!(validate_image_ref("rust:slim").is_ok());
        // (#838 regression guard) registry/org-path + digest refs — the charset
        // originally omitted '/' and rejected every real ref.
        assert!(validate_image_ref("ghcr.io/org/repo:tag").is_ok());
        assert!(validate_image_ref("docker.io/library/rust@sha256:abc123").is_ok());
        // image byte-cap boundary (was untested):
        assert!(validate_image_ref(&"a".repeat(MAX_WORK_IMAGE_BYTES)).is_ok());
        assert!(validate_image_ref(&"a".repeat(MAX_WORK_IMAGE_BYTES + 1)).is_err());
    }

    #[test]
    fn validate_image_ref_empty() {
        let err = validate_image_ref("").unwrap_err();
        assert!(err.to_string().contains("non-empty"));
    }

    #[test]
    fn validate_image_ref_leading_dash() {
        let err = validate_image_ref("--privileged").unwrap_err();
        assert!(err.to_string().contains("must not start with '-'"));
    }

    #[test]
    fn validate_image_ref_bad_char() {
        let err = validate_image_ref("rust:slim\0").unwrap_err();
        assert!(err.to_string().contains("invalid char"));
    }

    // ---- WorkJob::validate boundary tests ----

    #[test]
    fn validate_job_zero_timeout() {
        let mut job = make_valid_job();
        job.timeout_seconds = 0;
        let err = job.validate().unwrap_err();
        assert!(err.to_string().contains("non-zero"));
    }

    #[test]
    fn validate_job_over_cap_message() {
        let mut job = make_valid_job();
        job.message = "x".repeat(MAX_WORK_MESSAGE_BYTES + 1);
        let err = job.validate().unwrap_err();
        assert!(err.to_string().contains("exceeds"));
    }

    #[test]
    fn validate_job_over_cap_workdir() {
        let mut job = make_valid_job();
        job.workdir = Some("x".repeat(MAX_WORK_WORKDIR_BYTES + 1));
        let err = job.validate().unwrap_err();
        assert!(err.to_string().contains("exceeds"));
    }

    #[test]
    fn validate_job_invalid_image_leading_dash() {
        let mut job = make_valid_job();
        job.image = Some("--privileged".to_string());
        let err = job.validate().unwrap_err();
        assert!(err.to_string().contains("must not start with '-'"));
    }

    #[test]
    fn validate_job_invalid_image_empty() {
        let mut job = make_valid_job();
        job.image = Some("".to_string());
        let err = job.validate().unwrap_err();
        assert!(err.to_string().contains("non-empty"));
    }

    #[test]
    fn validate_job_invalid_image_bad_char() {
        let mut job = make_valid_job();
        job.image = Some("rust:slim\0".to_string());
        let err = job.validate().unwrap_err();
        assert!(err.to_string().contains("invalid char"));
    }

    #[test]
    fn validate_job_valid_image_accepted() {
        let mut job = make_valid_job();
        job.image = Some("rust:slim".to_string());
        assert!(job.validate().is_ok());
    }
}
