// (4.0) A mission recorded before 4.0 still shows each step's tokens and
// turns.
//
// Its day file spells step sessions `step-<id>` (and, from FLOW 1.43.0,
// `step-<id>-<mission>`), with no `payload.step_id` on the records that
// carry the step's tokens and turns. The viewer never parses a session id:
// the daemon names each step as `payload.step_id` when it serves
// `/flow-mission/<id>`. The body routed here is that served response,
// GENERATED by `wire_fixtures::flow_mission_legacy_archive_wire_shape` from
// raw 3.x records through the real router, so this spec and that test pin
// the archive end to end: drop the daemon's stamping and the fixture
// regenerates without `step_id`, and the meters below go blank.
const fs = require('fs');
const path = require('path');
const { test, expect } = require('@playwright/test');

const GEN = path.join(__dirname, '..', 'fixtures', 'generated');
const served = JSON.parse(fs.readFileSync(path.join(GEN, 'flow-mission-legacy-archive.json'), 'utf8'));

const MISSION_ID = 'review-1785400940-legacy';
const MISSION_RE = /\/flow-mission\/[^/?]+(\?.*)?$/;
const BACKFILL_RE = /\/flow\/\d{4}-\d{2}-\d{2}(?!\/stream)(\?.*)?$/;
const STREAM_RE = /\/flow\/\d{4}-\d{2}-\d{2}\/stream(\?.*)?$/;
const STARTED = Date.parse('2026-08-20T09:00:00Z') / 1000;

function graphSnapshot() {
  return {
    mission_id: MISSION_ID,
    mission_status: 'finalized',
    nodes: [
      { id: 'phase-a', kind: 'phase', label: 'Adjudicate', status: 'complete', depth: 0, steps: [] },
      {
        id: 'task-1', kind: 'task', label: 'Judge and verify', parentId: 'phase-a', status: 'complete', depth: 0,
        steps: [
          { id: 'judge-1', kind: 'review.judge', label: 'Judge', status: 'complete', startedTs: STARTED, completedTs: STARTED + 7, model: 'darkmux:gpt-oss-120b' },
          { id: 'verify-1', kind: 'review.verify', label: 'Verify', status: 'complete', startedTs: STARTED + 60, completedTs: STARTED + 66, model: 'darkmux:devstral-small-2-2512' },
        ],
      },
    ],
    edges: [],
    generated_at_ms: 0,
  };
}

test('a pre-4.0 archive served by the daemon still attributes tokens and turns to its steps', async ({ page }) => {
  const pageErrors = [];
  page.on('pageerror', (e) => pageErrors.push(String(e)));
  await page.setViewportSize({ width: 390, height: 900 });

  await page.route(`**/mission/${MISSION_ID}/graph.json`, (r) => r.fulfill({ contentType: 'application/json', body: JSON.stringify(graphSnapshot()) }));
  await page.route(MISSION_RE, (r) => r.fulfill({ contentType: 'application/json', body: JSON.stringify({ records: served, count: served.length, truncated: false, generated_at_ms: 0 }) }));
  await page.route(BACKFILL_RE, (r) => r.fulfill({ contentType: 'application/json', body: '[]' }));
  await page.route(STREAM_RE, (r) => r.fulfill({ contentType: 'text/event-stream', body: '' }));
  await page.goto(`/index-live.html#mission=${MISSION_ID}`);

  await page.locator('.tltask .tlt-hd').first().click();
  const judge = page.locator('.tlt-step', { has: page.locator('.smodel', { hasText: 'gpt-oss-120b' }) });
  const verify = page.locator('.tlt-step', { has: page.locator('.smodel', { hasText: 'devstral-small-2-2512' }) });
  await expect(judge).toHaveCount(1);
  await expect(verify).toHaveCount(1);

  // `step-judge-1`: the bare pre-1.43.0 spelling.
  await expect(judge.locator('.mn-step-meter')).toContainText('4 turns');
  await expect(judge.locator('.mn-step-meter .tok')).toContainText('5.0k');
  // `step-verify-1-<mission>`: the run-scoped FLOW 1.43.0 spelling.
  await expect(verify.locator('.mn-step-meter')).toContainText('2 turns');
  await expect(verify.locator('.mn-step-meter .tok')).toContainText('18');

  expect(pageErrors).toEqual([]);
});
