//! Load workload manifests by id from any of several known locations.
//! Search order: user dir → on-disk built-in template dirs → binary-embedded built-ins.
//!
//! **(#2553) The on-disk tier is NOT cwd-sensitive.** It used to
//! unconditionally search `<shell's cwd>/templates/builtin/workloads/` ahead
//! of the embedded tier, unscoped by anything the operator declared — the
//! sibling of #2432's mission-config fix, left unfixed there deliberately
//! and closed here. `darkmux lab run <id>` picked a different document
//! depending on which of an operator's several worktrees the shell happened
//! to be standing in, and — worse than the mission-config case — there was
//! no way to even TELL: `WorkloadSource` folded on-disk and embedded into a
//! single `Builtin` variant, so a workload resolving from cwd was
//! indistinguishable from the binary-embedded one. Closing #2553 is
//! therefore two changes: this file drops the cwd search (see
//! `builtin_dirs`), and `WorkloadSource` (`workloads::types`) now has
//! distinct `OnDisk`/`Embedded` variants so a resolution can actually be
//! reported — `lab::run::lab_run`'s per-run banner names the tier that won,
//! same as `mission launch`'s banner does for mission configs. The
//! sanctioned explicit path is unaffected: `DARKMUX_TEMPLATES_DIR` (or
//! `config.dirs.templates`) already sits at the TOP of `builtin_dirs` via
//! `darkmux_types::config_access::templates_override_dirs`, so "run this
//! checkout's templates" is one env var away, deliberately, rather than an
//! accident of `pwd`.
//!
//! **This is the on-disk (`builtin_dirs`) tier only — it does NOT make the
//! USER tier above it cwd-insensitive too.** `lab::run::lab_run` resolves
//! that tier via `paths::resolve(ResolveScope::Auto)`, which still returns
//! `<cwd>/.darkmux` when the shell happens to be standing inside a directory
//! that has one, so a workload can still resolve differently by cwd through
//! that tier. `mission_config::load` avoids this on its own user tier via
//! `ResolveScope::ForceUser` (#1012); doing the same here is tracked
//! separately as #2590, deliberately out of scope for this fix.

use crate::workloads::types::{LoadedWorkload, WorkloadManifest, WorkloadSource};
use anyhow::{Context, Result, anyhow, bail};
use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Workloads compiled into the binary at build time. Each entry is `(id, json)`
/// where `json` is the verbatim manifest. This makes `cargo install --path .`
/// self-contained — users don't need a checked-out source tree to use the
/// built-in workloads.
const EMBEDDED_WORKLOADS: &[(&str, &str)] = &[
    (
        "quick-q",
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/builtin/workloads/quick-q.json")),
    ),
    (
        "crawl-error-discard",
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/builtin/workloads/crawl-error-discard.json")),
    ),
    (
        "long-agentic",
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/builtin/workloads/long-agentic.json")),
    ),
    (
        "quick-coding",
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/builtin/workloads/quick-coding.json")),
    ),
    (
        "medium-coding",
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/builtin/workloads/medium-coding.json")),
    ),
    // (#1196) Tool-call bench — the sandbox is GENERATED by the provider
    // (fresh nonces per run), so unlike coding-task workloads it needs no
    // sibling seed dir and embeds cleanly.
    (
        "tool-bench",
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/builtin/workloads/tool-bench.json")),
    ),
    // (#1530) The quickstart workload the onboarding path names by id
    // (`skills/darkmux-lab-run` → `scripts/lab-init.sh` then `darkmux lab run
    // demo-quickstart`). It was shipped under templates/ but never listed
    // here, so it resolved only via the cwd-relative on-disk fallback — i.e.
    // from a source checkout and nowhere else, leaving every brew /
    // `cargo install` operator's first documented run failing "not found".
    // It embeds cleanly under `parse_str`'s rules: no `promptFile`, and
    // although it is `provider: coding-task` it declares NO `sandboxSeed`
    // (it binds a registered fixture + external sandbox instead), exactly
    // like the already-embedded `long-agentic`.
    (
        "demo-quickstart",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../templates/builtin/workloads/demo-quickstart.json"
        )),
    ),
];

fn find_embedded(id: &str) -> Option<&'static str> {
    EMBEDDED_WORKLOADS
        .iter()
        .find(|(name, _)| *name == id)
        .map(|(_, json)| *json)
}

/// Built-in template directories, in priority order. Override candidates come
/// from `env(DARKMUX_TEMPLATES_DIR)` then `config.dirs.templates` (#661 Slice 3),
/// prepended ahead of home/system.
///
/// **(#2553) This ON-DISK tier is deliberately NOT cwd-sensitive.** An
/// earlier version of this function also pushed
/// `<cwd>/templates/builtin/workloads`, so the document that won depended on
/// which directory the shell happened to be in when `darkmux` ran —
/// invisible to an operator who didn't already know to suspect it, and
/// dangerous specifically when the cwd's document shares the binary's schema
/// but has DIFFERENT content (a stale or half-edited worktree), because that
/// case parses cleanly with no error to catch it. Same reasoning as
/// `mission_config::load::builtin_dirs` (#2432). The explicit
/// `templates_override_dirs()` tier above already gives an operator who
/// wants "this checkout's templates" exactly that, on purpose:
/// `DARKMUX_TEMPLATES_DIR=$PWD/templates/builtin`.
///
/// **This does NOT make workload resolution as a whole cwd-insensitive —
/// only this one tier.** The USER tier (searched by [`load`] before this
/// function ever runs) still comes from `lab::run::lab_run`'s
/// `paths::resolve(ResolveScope::Auto)`, which resolves to `<cwd>/.darkmux`
/// whenever that directory exists — so a `./.darkmux/workloads/<id>.json`
/// sitting in the shell's cwd still wins over every tier this function
/// searches, same as it always did. `mission_config::load` closed that same
/// gap on its own user tier by resolving through `ResolveScope::ForceUser`
/// instead (#1012, `crate::loader::mission_configs_dir`); `lab_run`'s user
/// tier was deliberately left on `Auto` here and stays cwd-sensitive by
/// design, tracked separately as #2590.
fn builtin_dirs() -> Vec<PathBuf> {
    let mut dirs = Vec::new();
    for base in darkmux_types::config_access::templates_override_dirs() {
        dirs.push(base.join("workloads"));
    }
    if let Some(home) = dirs::home_dir() {
        dirs.push(home.join(".darkmux").join("templates").join("builtin").join("workloads"));
    }
    dirs.push(PathBuf::from("/usr/local/share/darkmux/templates/builtin/workloads"));
    dirs
}

pub(crate) fn load(id: &str, user_dir: Option<&Path>) -> Result<LoadedWorkload> {
    if let Some(udir) = user_dir {
        let user_workloads = udir.join("workloads");
        if let Some(p) = find_in_dir(&user_workloads, id) {
            return parse(&p, WorkloadSource::User);
        }
    }
    for d in builtin_dirs() {
        if let Some(p) = find_in_dir(&d, id) {
            return parse(&p, WorkloadSource::OnDisk);
        }
    }
    if let Some(json) = find_embedded(id) {
        return parse_str(json, id);
    }
    let avail = list_available(user_dir);
    let listed = if avail.is_empty() {
        "(none)".to_string()
    } else {
        avail.join(", ")
    };
    bail!("workload \"{id}\" not found. Available: {listed}")
}

pub fn list_available(user_dir: Option<&Path>) -> Vec<String> {
    let mut set: BTreeSet<String> = BTreeSet::new();
    let mut all_dirs: Vec<PathBuf> = Vec::new();
    if let Some(d) = user_dir {
        all_dirs.push(d.join("workloads"));
    }
    all_dirs.extend(builtin_dirs());
    for dir in all_dirs {
        if !dir.exists() {
            continue;
        }
        let Ok(entries) = fs::read_dir(&dir) else { continue };
        for entry in entries.flatten() {
            let path = entry.path();
            let Some(name) = path.file_name().and_then(|n| n.to_str()) else { continue };
            if path.is_file() && name.ends_with(".json") {
                set.insert(name.trim_end_matches(".json").to_string());
            } else if path.is_dir() && path.join("workload.json").exists() {
                set.insert(name.to_string());
            }
        }
    }
    for (id, _) in EMBEDDED_WORKLOADS {
        set.insert((*id).to_string());
    }
    set.into_iter().collect()
}

fn find_in_dir(dir: &Path, id: &str) -> Option<PathBuf> {
    if !dir.exists() {
        return None;
    }
    let flat = dir.join(format!("{id}.json"));
    if flat.is_file() {
        return Some(flat);
    }
    let nested = dir.join(id).join("workload.json");
    if nested.is_file() {
        return Some(nested);
    }
    None
}

fn parse(path: &Path, source: WorkloadSource) -> Result<LoadedWorkload> {
    let raw = fs::read_to_string(path)
        .with_context(|| format!("reading workload manifest at {}", path.display()))?;
    let manifest: WorkloadManifest = serde_json::from_str(&raw)
        .with_context(|| format!("parsing workload JSON at {}", path.display()))?;
    let base_dir = path
        .parent()
        .ok_or_else(|| anyhow!("manifest has no parent dir: {}", path.display()))?
        .to_path_buf();
    Ok(LoadedWorkload {
        manifest,
        manifest_path: path.to_path_buf(),
        base_dir,
        source,
    })
}

/// Parse a workload manifest from an in-memory JSON string. Used for embedded
/// (binary-baked) workloads. The synthesized manifest_path / base_dir use an
/// `<embedded>` sentinel that does NOT correspond to a real filesystem path:
///
/// - Workloads that reference `promptFile` cannot be embedded (no resolvable
///   base_dir to read the file from).
/// - Coding-task workloads cannot be embedded either — they expect a sandbox
///   seed directory to copy from, which the sentinel can't provide. Embedding
///   one would silently run with an empty sandbox.
///
/// Anything that needs on-disk resources should be shipped as a directory
/// under `templates/builtin/workloads/` or installed to `~/.darkmux/...`.
fn parse_str(raw: &str, id: &str) -> Result<LoadedWorkload> {
    let manifest: WorkloadManifest = serde_json::from_str(raw)
        .with_context(|| format!("parsing embedded workload \"{id}\""))?;
    if manifest.workload.prompt_file.is_some() {
        bail!(
            "embedded workload \"{id}\" uses promptFile, which has no resolvable base_dir. \
             Inline the prompt or ship the workload on-disk instead."
        );
    }
    // Coding-task workloads can be embedded only if they don't explicitly
    // declare a sandbox seed — i.e., they use an external on-disk sandbox
    // (typically via the `DARKMUX_SANDBOX_<workload>` env var). A workload
    // that depends on a seed directory must ship as on-disk because
    // `<embedded>/<id>/sandbox` won't resolve on the user's filesystem.
    if manifest.workload.provider == "coding-task"
        && manifest.workload.sandbox_seed.is_some()
    {
        bail!(
            "embedded workload \"{id}\" uses provider=coding-task with an explicit sandboxSeed, \
             which has no resolvable base_dir. Drop the sandboxSeed field (so the workload uses \
             external sandbox via DARKMUX_SANDBOX_<workload>), or ship it as a directory under \
             templates/builtin/workloads/<id>/."
        );
    }
    let base = PathBuf::from(format!("<embedded>/{id}"));
    Ok(LoadedWorkload {
        manifest,
        manifest_path: base.join("workload.json"),
        base_dir: base,
        source: WorkloadSource::Embedded,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn write(path: &Path, contents: &str) {
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, contents).unwrap();
    }

    fn manifest_json(id: &str) -> String {
        format!(
            r#"{{"workload":{{"id":"{id}","provider":"prompt","prompt":"hello world"}}}}"#
        )
    }

    /// RAII guard that changes the process cwd for the test's duration and
    /// restores it on drop — mirrors `mission_config::load`'s test-only
    /// `CwdGuard` (#2432). Every caller MUST be `#[serial_test::serial]` —
    /// cwd is a process-global resource, and `serial_test` only coordinates
    /// among ANNOTATED tests, not any unannotated test elsewhere in this
    /// crate that happens to read/write cwd too. RAII (not manual
    /// set/restore) matters here specifically because these tests assert on
    /// the fix under test: an assertion panic mid-test must still restore
    /// cwd, or a red-proof run (which is EXPECTED to panic when the fix is
    /// reverted) leaks the temp cwd into every test that runs after it in
    /// the same `cargo test` process.
    struct CwdGuard {
        prev: PathBuf,
    }

    impl CwdGuard {
        fn new(dir: &Path) -> Self {
            let prev = env::current_dir().unwrap();
            env::set_current_dir(dir).unwrap();
            Self { prev }
        }
    }

    impl Drop for CwdGuard {
        fn drop(&mut self) {
            let _ = env::set_current_dir(&self.prev);
        }
    }

    /// RAII guard for a single process env var: sets it for the test's
    /// duration and restores the PRIOR value (or removes it) on drop, for
    /// the same red-proof-must-still-clean-up reason as `CwdGuard`.
    struct EnvVarGuard {
        key: &'static str,
        prev: Option<std::ffi::OsString>,
    }

    impl EnvVarGuard {
        fn set(key: &'static str, value: impl AsRef<std::ffi::OsStr>) -> Self {
            let prev = env::var_os(key);
            unsafe { env::set_var(key, value) };
            Self { key, prev }
        }
    }

    impl Drop for EnvVarGuard {
        fn drop(&mut self) {
            unsafe {
                match &self.prev {
                    Some(v) => env::set_var(self.key, v),
                    None => env::remove_var(self.key),
                }
            }
        }
    }

    #[test]
    fn loads_flat_json_from_user_dir() {
        let tmp = TempDir::new().unwrap();
        let user = tmp.path();
        write(&user.join("workloads/my-task.json"), &manifest_json("my-task"));
        let loaded = load("my-task", Some(user)).unwrap();
        assert_eq!(loaded.manifest.workload.id, "my-task");
        assert_eq!(loaded.source, WorkloadSource::User);
        assert_eq!(loaded.base_dir, user.join("workloads"));
    }

    #[test]
    fn loads_nested_workload_json() {
        let tmp = TempDir::new().unwrap();
        let user = tmp.path();
        write(&user.join("workloads/big-task/workload.json"), &manifest_json("big-task"));
        let loaded = load("big-task", Some(user)).unwrap();
        assert_eq!(loaded.manifest.workload.id, "big-task");
        assert_eq!(loaded.base_dir, user.join("workloads/big-task"));
    }

    #[serial_test::serial]
    #[test]
    fn list_available_returns_sorted_unique() {
        let tmp = TempDir::new().unwrap();
        let user = tmp.path();
        write(&user.join("workloads/zebra.json"), &manifest_json("zebra"));
        write(&user.join("workloads/alpha.json"), &manifest_json("alpha"));
        write(&user.join("workloads/beta/workload.json"), &manifest_json("beta"));
        // Point templates dir at an empty path so builtins don't pollute the test.
        let empty = tmp.path().join("no-builtins-here");
        unsafe { env::set_var("DARKMUX_TEMPLATES_DIR", empty.to_str().unwrap()) };
        // Also chdir to a dir without templates/ so the cwd lookup misses.
        let prev = env::current_dir().unwrap();
        env::set_current_dir(tmp.path()).unwrap();
        let avail = list_available(Some(user));
        env::set_current_dir(prev).unwrap();
        unsafe { env::remove_var("DARKMUX_TEMPLATES_DIR") };
        // Embedded workloads (compiled into the binary) are always present in
        // addition to whatever's on disk. Filter them out for this test, which
        // asserts on-disk discovery + sorting only.
        let on_disk_only: Vec<String> = avail
            .into_iter()
            .filter(|id| !EMBEDDED_WORKLOADS.iter().any(|(eid, _)| eid == id))
            .collect();
        assert_eq!(on_disk_only, vec!["alpha", "beta", "zebra"]);
    }

    #[test]
    fn missing_workload_errors_with_listing() {
        let tmp = TempDir::new().unwrap();
        let user = tmp.path();
        write(&user.join("workloads/known.json"), &manifest_json("known"));
        let err = load("not-here", Some(user)).unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("not found"));
        assert!(msg.contains("known"));
    }

    #[serial_test::serial]
    #[test]
    fn missing_workload_with_no_workloads_says_none() {
        let tmp = TempDir::new().unwrap();
        let prev = env::current_dir().unwrap();
        env::set_current_dir(tmp.path()).unwrap();
        unsafe { env::set_var("DARKMUX_TEMPLATES_DIR", tmp.path().join("nope")) };

        let err = load("anything", None).unwrap_err();

        unsafe { env::remove_var("DARKMUX_TEMPLATES_DIR") };
        env::set_current_dir(prev).unwrap();

        // Embedded workloads now mean Available is never literally "(none)";
        // the listing should still surface them so users can see what's offered.
        let msg = err.to_string();
        assert!(msg.contains("not found"));
        for (id, _) in EMBEDDED_WORKLOADS {
            assert!(
                msg.contains(id),
                "expected embedded workload \"{id}\" in error listing: {msg}"
            );
        }
    }

    #[test]
    fn malformed_json_errors_with_path() {
        let tmp = TempDir::new().unwrap();
        let user = tmp.path();
        write(&user.join("workloads/broken.json"), "{not: valid json");
        let err = load("broken", Some(user)).unwrap_err();
        assert!(err.to_string().contains("parsing workload JSON"));
    }

    #[test]
    fn missing_required_field_errors() {
        let tmp = TempDir::new().unwrap();
        let user = tmp.path();
        write(&user.join("workloads/no-id.json"), r#"{"workload":{"provider":"prompt"}}"#);
        let err = load("no-id", Some(user)).unwrap_err();
        assert!(err.to_string().contains("parsing workload JSON"));
    }

    #[test]
    fn user_dir_takes_priority_over_builtin() {
        let tmp = TempDir::new().unwrap();
        write(
            &tmp.path().join("workloads/quick-q.json"),
            &manifest_json("quick-q"),
        );
        let loaded = load("quick-q", Some(tmp.path())).unwrap();
        assert_eq!(loaded.source, WorkloadSource::User);
    }

    // `serial_test` coordinates only among ANNOTATED tests, so a reader of a
    // process-wide env var needs the guard just as much as a writer does.
    // Unguarded, this raced `missing_workload_with_no_workloads_says_none`
    // (which sets the same var, under the guard) and read its `.../nope`
    // path instead of its own — seen on CI, not reproducible locally at
    // 6/6 runs either way, which is what a scheduling-dependent race looks
    // like rather than evidence that it is gone.
    #[serial_test::serial]
    #[test]
    fn builtin_dirs_include_env_override() {
        unsafe { env::set_var("DARKMUX_TEMPLATES_DIR", "/tmp/test-templates") };
        let dirs = builtin_dirs();
        unsafe { env::remove_var("DARKMUX_TEMPLATES_DIR") };
        assert_eq!(
            dirs.first().unwrap(),
            &PathBuf::from("/tmp/test-templates/workloads")
        );
    }

    // ─── parse_str (embedded-workload parser) ────────────────────────

    #[test]
    fn parse_str_loads_valid_inline_prompt() {
        let raw = r#"{"workload":{"id":"hello","provider":"prompt","prompt":"hi"}}"#;
        let loaded = parse_str(raw, "hello").unwrap();
        assert_eq!(loaded.manifest.workload.id, "hello");
        assert_eq!(loaded.manifest.workload.provider, "prompt");
        assert_eq!(loaded.manifest.workload.prompt.as_deref(), Some("hi"));
        // Source is Embedded and the sentinel base_dir is the literal `<embedded>/<id>` form
        assert_eq!(loaded.source, WorkloadSource::Embedded);
        assert_eq!(loaded.base_dir, PathBuf::from("<embedded>/hello"));
    }

    #[test]
    fn parse_str_rejects_prompt_file() {
        let raw =
            r#"{"workload":{"id":"x","provider":"prompt","promptFile":"prompt.txt"}}"#;
        let err = parse_str(raw, "x").unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("promptFile"), "got: {msg}");
        assert!(msg.contains("\"x\""), "got: {msg}");
    }

    /// Coding-task with no explicit sandbox seed embeds OK (uses external
    /// sandbox via env var).
    #[test]
    fn parse_str_allows_coding_task_without_seed() {
        let raw = r#"{"workload":{"id":"y","provider":"coding-task","prompt":"do it"}}"#;
        let loaded = parse_str(raw, "y").unwrap();
        assert_eq!(loaded.manifest.workload.provider, "coding-task");
    }

    /// Coding-task that ALSO declares sandboxSeed cannot be embedded.
    #[test]
    fn parse_str_rejects_coding_task_with_sandbox_seed() {
        let raw = r#"{"workload":{"id":"y","provider":"coding-task","prompt":"do it","sandboxSeed":"sandbox"}}"#;
        let err = parse_str(raw, "y").unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("coding-task"), "got: {msg}");
        assert!(msg.contains("sandboxSeed"), "got: {msg}");
    }

    #[test]
    fn parse_str_errors_on_malformed_json() {
        let err = parse_str("{not: valid", "broken").unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("parsing embedded workload"), "got: {msg}");
        assert!(msg.contains("\"broken\""), "got: {msg}");
    }

    /// Phase B compaction workload: verify the embedded manifest parses
    /// cleanly, ships the expected sandbox layout (4 src modules + 3
    /// partial-coverage test files + 2 __init__.py), and points at the
    /// `coder` role with a unittest-discover verify command. Catches
    /// regressions where someone edits the manifest content and breaks
    /// either the JSON shape or the gap-list shape that makes it useful
    /// for compaction-exercise dispatch.
    #[test]
    fn medium_coding_embedded_manifest_has_expected_shape() {
        let json = find_embedded("medium-coding").expect("medium-coding should be embedded");
        let manifest: WorkloadManifest =
            serde_json::from_str(json).expect("medium-coding manifest should parse");
        let w = &manifest.workload;
        assert_eq!(w.id, "medium-coding");
        assert_eq!(w.provider, "coding-task");
        assert_eq!(w.role.as_deref(), Some("coder"));
        let expected_files = [
            "src/__init__.py",
            "src/parser.py",
            "src/validator.py",
            "src/aggregator.py",
            "src/storage.py",
            "tests/__init__.py",
            "tests/test_parser.py",
            "tests/test_validator.py",
            "tests/test_aggregator.py",
        ];
        for path in expected_files {
            assert!(
                w.setup_content.contains_key(path),
                "setupContent missing expected file: {path}"
            );
        }
        // No test_storage.py — storage is the whole-file-gap module by design.
        assert!(
            !w.setup_content.contains_key("tests/test_storage.py"),
            "tests/test_storage.py should NOT ship (it's the whole-file gap)"
        );
        let verify = w.verify.as_ref().expect("verify spec required");
        let cmd = verify.command.as_deref().expect("verify command required");
        assert!(
            cmd.contains("unittest discover"),
            "verify command should use unittest discover: {cmd}"
        );
        assert_eq!(verify.cwd.as_deref(), Some("${SANDBOX_DIR}"));
        assert_eq!(verify.must_contain, vec!["OK".to_string()]);
        assert_eq!(verify.must_not_contain, vec!["FAILED".to_string()]);
        // Lock the prompt to its anchor heading + the storage-module reference.
        // The storage reference is load-bearing: it ties the prompt's gap list
        // to the actual file layout that the file-presence assertions above
        // validate. If someone reorganizes modules without updating the
        // prompt, this fails — preventing operationally-confusing dispatches
        // where the prompt promises files that don't exist.
        let prompt = w.prompt.as_deref().expect("prompt required");
        assert!(
            prompt.contains("COVERAGE AUDIT"),
            "prompt should retain its anchor heading"
        );
        assert!(
            prompt.contains("${SANDBOX_DIR}/src/storage.py"),
            "prompt should reference the storage module (the whole-file gap)"
        );
    }

    /// Forward-compat: asking for an embedded workload by id resolves it from
    /// the binary even when there's no on-disk template anywhere.
    #[serial_test::serial]
    #[test]
    fn embedded_workload_resolves_with_no_on_disk_templates() {
        let tmp = TempDir::new().unwrap();
        let prev = env::current_dir().unwrap();
        env::set_current_dir(tmp.path()).unwrap();
        unsafe { env::set_var("DARKMUX_TEMPLATES_DIR", tmp.path().join("nope")) };
        let result = load("quick-q", None);
        unsafe { env::remove_var("DARKMUX_TEMPLATES_DIR") };
        env::set_current_dir(prev).unwrap();
        let loaded = result.expect("quick-q should load from the embedded const");
        assert_eq!(loaded.manifest.workload.id, "quick-q");
        assert_eq!(loaded.source, WorkloadSource::Embedded);
    }

    /// (#1530) The ONBOARDING workload specifically — `skills/darkmux-lab-run`
    /// tells a brand-new operator to run `darkmux lab run demo-quickstart`,
    /// and a brew / `cargo install` operator has no source checkout, so the
    /// cwd-relative on-disk fallback can't save it. It shipped under
    /// templates/ but was absent from `EMBEDDED_WORKLOADS`, making the first
    /// documented command fail "not found" for exactly the audience following
    /// the docs. This pins the binary-only resolution rather than the const's
    /// membership, so it fails for the reason an operator would feel.
    #[serial_test::serial]
    #[test]
    fn onboarding_demo_quickstart_resolves_with_no_on_disk_templates() {
        let tmp = TempDir::new().unwrap();
        let prev = env::current_dir().unwrap();
        env::set_current_dir(tmp.path()).unwrap();
        unsafe { env::set_var("DARKMUX_TEMPLATES_DIR", tmp.path().join("nope")) };
        let result = load("demo-quickstart", None);
        unsafe { env::remove_var("DARKMUX_TEMPLATES_DIR") };
        env::set_current_dir(prev).unwrap();
        let loaded = result.expect(
            "demo-quickstart is the documented first run — it must resolve from the binary \
             on a machine with no source checkout",
        );
        assert_eq!(loaded.manifest.workload.id, "demo-quickstart");
        assert_eq!(loaded.source, WorkloadSource::Embedded);
        // It binds the built-in fixture rather than a sandbox seed — the
        // property that makes it embeddable under `parse_str`'s rules.
        assert!(
            loaded.manifest.workload.sandbox_seed.is_none(),
            "demo-quickstart must not declare a sandboxSeed, or it can't be embedded"
        );
    }

    // ─── #2553 — the on-disk tier must NOT be cwd-sensitive ──────────────
    // Sibling of `mission_config::load`'s #2432 tests, same shape. Every
    // test below isolates BOTH `$HOME` (so `dirs::home_dir()` can't pick up
    // a real `~/.darkmux/templates/builtin/workloads/` on the operator's
    // machine — never read or write the real one) and
    // `DARKMUX_TEMPLATES_DIR` (so only the one tier under test is live).

    /// The precedence claim itself, not just "something loaded". A valid
    /// "quick-q" workload with DIFFERENT content sits at
    /// `<cwd>/templates/builtin/workloads/quick-q.json` — the exact shape
    /// of a stale worktree's checked-out templates — with no user-tier
    /// copy and no `DARKMUX_TEMPLATES_DIR` override. `load("quick-q",
    /// None)` must resolve the EMBEDDED built-in, not the cwd document.
    /// Red-proved: reverting the #2553 fix (restoring the cwd push in
    /// `builtin_dirs`) makes this resolve `WorkloadSource::OnDisk` with the
    /// cwd document's prompt instead of the embedded one's.
    #[test]
    #[serial_test::serial]
    fn on_disk_tier_ignores_cwd_templates() {
        let home_tmp = TempDir::new().unwrap();
        let _home_guard = EnvVarGuard::set("HOME", home_tmp.path());
        let _templates_guard =
            EnvVarGuard::set("DARKMUX_TEMPLATES_DIR", home_tmp.path().join("nope"));

        let cwd_tmp = TempDir::new().unwrap();
        write(
            &cwd_tmp.path().join("templates/builtin/workloads/quick-q.json"),
            r#"{"workload":{"id":"quick-q","provider":"prompt","prompt":"cwd should never win"}}"#,
        );
        let _cwd_guard = CwdGuard::new(cwd_tmp.path());

        let loaded =
            load("quick-q", None).expect("quick-q must still resolve via the embedded tier");
        assert_eq!(
            loaded.source,
            WorkloadSource::Embedded,
            "a document sitting in cwd's templates/ must not outrank the embedded built-in"
        );
        assert_ne!(
            loaded.manifest.workload.prompt.as_deref(),
            Some("cwd should never win"),
            "the cwd-local document's content must not win"
        );
    }

    /// A synthetic id with NO user, embedded, or `DARKMUX_TEMPLATES_DIR`
    /// counterpart, present ONLY under `<cwd>/templates/builtin/workloads/`
    /// — the shape of a document that resolves purely because the shell
    /// happens to be standing inside some worktree. `load()` must report it
    /// not found, not silently resolve it from cwd.
    #[test]
    #[serial_test::serial]
    fn on_disk_tier_does_not_resolve_a_cwd_only_id() {
        let home_tmp = TempDir::new().unwrap();
        let _home_guard = EnvVarGuard::set("HOME", home_tmp.path());
        let _templates_guard =
            EnvVarGuard::set("DARKMUX_TEMPLATES_DIR", home_tmp.path().join("nope"));

        let cwd_tmp = TempDir::new().unwrap();
        write(
            &cwd_tmp
                .path()
                .join("templates/builtin/workloads/cwd-only-2553.json"),
            &manifest_json("cwd-only-2553"),
        );
        let _cwd_guard = CwdGuard::new(cwd_tmp.path());

        let err = load("cwd-only-2553", None).unwrap_err();
        assert!(err.to_string().contains("not found"), "{err}");
    }

    /// The escape-hatch verification, by EXECUTION not by reading. This is
    /// the fix's own justification for removing the cwd tier outright
    /// rather than scoping it ("the explicit override already sits at the
    /// top of `builtin_dirs`") — nothing else in this module proves the
    /// override actually reaches workload resolution. `DARKMUX_TEMPLATES_DIR`
    /// holds a "quick-q" document with DIFFERENT content than the embedded
    /// built-in, no user-tier copy exists, and no cwd document is involved
    /// at all — the override must still beat the embedded tier.
    ///
    /// Red-proved by hoisting the `find_embedded` check above the
    /// `builtin_dirs()` loop in [`load`]: that mutation disables the
    /// override outright (the embedded document wins over any
    /// `DARKMUX_TEMPLATES_DIR` the operator sets), and this is the only
    /// test in this module that goes red for it —
    /// `user_dir_takes_priority_over_builtin` can't catch it (it never
    /// exercises the on-disk tier at all), and neither cwd test above can
    /// (their synthetic/embedded ids have no `DARKMUX_TEMPLATES_DIR`
    /// counterpart to be shadowed by).
    #[test]
    #[serial_test::serial]
    fn on_disk_override_beats_embedded_for_a_known_id() {
        let home_tmp = TempDir::new().unwrap();
        let _home_guard = EnvVarGuard::set("HOME", home_tmp.path());

        let templates_tmp = TempDir::new().unwrap();
        write(
            &templates_tmp.path().join("workloads/quick-q.json"),
            r#"{"workload":{"id":"quick-q","provider":"prompt","prompt":"on-disk override should win"}}"#,
        );
        let _templates_guard = EnvVarGuard::set("DARKMUX_TEMPLATES_DIR", templates_tmp.path());

        let loaded =
            load("quick-q", None).expect("quick-q must resolve via the on-disk override");
        assert_eq!(loaded.source, WorkloadSource::OnDisk);
        assert_eq!(
            loaded.manifest.workload.prompt.as_deref(),
            Some("on-disk override should win")
        );
    }
}
