#!/usr/bin/env node
/**
 * Screenshot every lens of the running demo world.
 *
 *   ./serve.py &                      # must already be up
 *   node shoot.mjs                    # -> ../../screenshots/*.png
 *   node shoot.mjs --only machine,fleet
 *   node shoot.mjs --mobile
 *
 * Playwright, not `chrome --headless --screenshot`: the viewer polls forever,
 * so `--virtual-time-budget` never reaches idle and the shot never fires
 * (measured — it hung past two minutes on the fleet lens). Playwright lets the
 * wait be a CONDITION rather than a duration, so each lens is captured once
 * its own content is actually on screen.
 *
 * Reuses ui/node_modules' playwright — already a dev dependency of this repo,
 * no new install surface.
 */
import { chromium } from "../../ui/node_modules/playwright/index.mjs";
import { mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");

/** name -> { route, ready }. `ready` is a selector that only exists once the
 * lens has real data, so the shutter waits on CONTENT, not on a timer. */
const SHOTS = {
  fleet:           { route: "#lens=fleet",                      ready: ".fleet-card, [class*=fleetcard]" },
  machine:         { route: "#lens=machine",                    ready: ".mm-row, [class*=memcard], [class*=mm-]" },
  runs:            { route: "#lens=runs",                       ready: "table tbody tr, [class*=runrow]" },
  // doctor is a MANUAL panel (MANUAL_PANELS in lenses/console/panels.ts): it
  // probes the machine, so selecting the tab deliberately does NOT fetch —
  // #1286, the observer must not join the observed. Without the click the shot
  // is just the "not run yet" placeholder, which is what the first run caught.
  "console-doctor":{ route: "#lens=console&panel=doctor", ready: "#stage",
                     click: "button:has-text('run')", after: "pre, .ansi, code" },
  "console-runs":  { route: "#lens=console&panel=run-list",      ready: "#stage" },
  // The console's other panels, chosen because each fills a DOC gap rather
  // than because it was handy: `role list` is the only view of the role
  // library anywhere, `config list` shows the visible-defaults philosophy as
  // an actual file, and `flow status` shows the sink composition the
  // observability guide describes in prose. `mission-status` and
  // `lab-fixture-list` are deliberately absent — both render an empty state
  // in the demo world, and an empty panel teaches nothing.
  "console-roles": { route: "#lens=console&panel=role-list",     ready: "#stage" },
  "console-config":{ route: "#lens=console&panel=config-list",   ready: "#stage" },
  "console-flow":  { route: "#lens=console&panel=flow-status",   ready: "#stage" },
};

/** Shots with a fixed viewport of their own, independent of --width/--height.
 * The social card is 1200x630 because that is what OG/Twitter consume; making
 * it a NAMED shot rather than a one-off crop means it is regenerated by the
 * same command as everything else and can never drift from the UI again —
 * which is exactly how the previous card ended up advertising a two-machine
 * fleet and a headline figure the lens had stopped rendering. */
const FIXED = {
  // Shot TALL and clipped to 1200x630 rather than shot at 630. At 630 the
  // right column has to cram the record-detail panel and the event stream into
  // one short space, and the detail panel gets clipped mid-line THROUGH the
  // events header — which reads as a rendering bug in the one image most
  // people see first. Giving the page real height lets both panels lay out
  // properly, then the clip takes the top band.
  "og-card": {
    route: "#lens=fleet", ready: ".fleet-card, [class*=fleetcard]",
    w: 1200, h: 1000, clip: { x: 0, y: 0, width: 1200, height: 630 },
  },
};

const args = process.argv.slice(2);
const opt = (n, d) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : d; };
const base   = opt("--base", "http://localhost:8799");
const outDir = opt("--out", join(ROOT, "screenshots"));
const only   = opt("--only", null);
const width  = Number(opt("--width", 1440));
const height = Number(opt("--height", 900));
const dpr    = Number(opt("--dpr", 2));
const mobile = args.includes("--mobile");
// `--copy-to <dir>` mirrors the finished shots somewhere else — in practice an
// iCloud-synced folder, so they land on a phone without a transfer step. The
// shots stay in `screenshots/` either way; this only ever adds a copy, so a
// bad path costs a warning rather than the run.
const copyTo = opt("--copy-to", null);

mkdirSync(outDir, { recursive: true });

// Pin the detail shot to the run that is actually in flight: that is the one
// with a live pulse, a ticking clock and a RUNNING banner — the version of
// the lens worth putting in the docs.
let runs = [];
try {
  runs = (await (await fetch(`${base}/runs`)).json()).runs ?? [];
} catch {
  console.error(`no demo world at ${base} — start ./serve.py first`);
  process.exit(1);
}
const target = runs.find((r) => r.status === "running") ?? runs.find((r) => r.status === "complete");
if (target) SHOTS["run-detail"] = { route: `#lens=dispatch&dispatch=${target.id}`, ready: "#stage" };
else console.error("  ! no runs found; skipping run-detail");

const want = only ? new Set(only.split(",")) : new Set([...Object.keys(SHOTS), ...Object.keys(FIXED)]);
const unknown = [...want].filter((n) => !SHOTS[n] && !FIXED[n]);
if (unknown.length) {
  console.error(`unknown shot(s): ${unknown.join(", ")}\navailable: ${Object.keys(SHOTS).join(", ")}`);
  process.exit(1);
}

// The INSTALLED Chrome, not Playwright's bundled Chromium. The UI's mono
// stack is `ui-monospace, SFMono-Regular, monospace` (styles.css:974);
// `ui-monospace` resolves to SF Mono in real Chrome on macOS, and to a
// generic fallback in bundled Chromium — so a bundled capture is visibly a
// DIFFERENT TYPEFACE from what every reader of the docs sees. A screenshot
// whose font does not match the product is a wrong screenshot.
let browser, usingChannel = "chrome";
try {
  browser = await chromium.launch({ channel: "chrome" });
} catch {
  usingChannel = "bundled chromium";
  console.error("  ! Google Chrome not available — falling back to bundled Chromium.");
  console.error("  ! Fonts will NOT match the product; do not ship these to the docs.");
  browser = await chromium.launch();
}
let failed = 0;

async function shoot(name, route, ready, w, h, suffix = "", click = null, after = null, clip = null) {
  const ctx = await browser.newContext({
    viewport: { width: w, height: h },
    deviceScaleFactor: dpr,
    colorScheme: "dark",
    reducedMotion: "reduce",   // freeze the pulse mid-frame instead of blurring it
  });
  const page = await ctx.newPage();
  const file = join(outDir, `${name}${suffix}.png`);
  try {
    await page.goto(`${base}/${route}`, { waitUntil: "domcontentloaded", timeout: 30000 });
    // Content first, then one settle beat for late-arriving polls (host
    // telemetry, the ledger gather) to paint before the shutter.
    await page.waitForSelector(ready, { timeout: 20000 }).catch(() => {});
    if (click) {
      await page.locator(click).first().click({ timeout: 10000 }).catch(() => {});
      if (after) await page.waitForSelector(after, { timeout: 20000 }).catch(() => {});
    }
    await page.waitForTimeout(2500);
    await page.screenshot({ path: file, fullPage: false, ...(clip ? { clip } : {}) });
    console.log(`  ok   ${(name + suffix).padEnd(22)} ${w}x${h}@${dpr}x`);
  } catch (e) {
    failed++;
    console.log(`  FAIL ${(name + suffix).padEnd(22)} ${String(e).split("\n")[0].slice(0, 120)}`);
  } finally {
    await ctx.close();
  }
}

console.log(`shooting ${want.size} lens(es) from ${base} (${usingChannel})`);
for (const [name, f] of Object.entries(FIXED)) {
  if (only && !want.has(name)) continue;
  await shoot(name, f.route, f.ready, f.w, f.h, "", null, null, f.clip);
}
// The console panels are NOT shot on mobile (operator's call). `doctor`
// reserves 27 columns for its marker and check name before the message
// starts, and both the daemon's `clamp_cols` and doctor's own
// `output_width()` floor around 36-40 — so on a ~45-column phone panel the
// message gets ~18 columns and still overflows, however honestly it wraps.
// That is the remaining half of #1995 and its fix is the mobile `pre-wrap`
// rule, not the renderer. Shooting it anyway would put a picture of a known
// unfixed defect in the docs; skipping it is not hiding the bug (the issue
// tracks it) but it is not advertising it either.
const SKIP_ON_MOBILE = new Set([
  "console-doctor", "console-runs", "console-roles", "console-config", "console-flow",
]);

for (const [name, { route, ready, click, after }] of Object.entries(SHOTS)) {
  if (!want.has(name)) continue;
  await shoot(name, route, ready, width, height, "", click, after);
  if (mobile && !SKIP_ON_MOBILE.has(name)) {
    await shoot(name, route, ready, 390, 844, "-mobile", click, after);
  }
}
await browser.close();

if (copyTo) {
  const { cpSync, mkdirSync, readdirSync } = await import("node:fs");
  try {
    mkdirSync(copyTo, { recursive: true });
    const shots = readdirSync(outDir).filter((f) => f.endsWith(".png"));
    for (const f of shots) cpSync(join(outDir, f), join(copyTo, f));
    console.log(`copied ${shots.length} png(s) -> ${copyTo}`);
  } catch (e) {
    console.error(`  ! copy to ${copyTo} failed: ${String(e).split("\n")[0]}`);
  }
}

console.log(`\n${failed ? `${failed} failed` : "done"} -> ${outDir}`);
process.exit(failed ? 1 : 0);
