//! The pre-4.0 archive golden (`tests/flow-archive-golden/` at the repo root).
//!
//! `2026-08-20.jsonl` holds every action spelling 4.0 retired (the spaced
//! bookends, `note`, `tier-decision`, `verdict: <v>`, `sprint start`, ...),
//! actions retired with no current equivalent (`telemetry.process`,
//! `funnel.step`, `crawl.finding`), the dotted lineage that already used the
//! current spelling, usage records, a schema header, and one action no build
//! knows (`future.thing`). Its uids are fake.
//!
//! `2026-08-20.upgraded.jsonl` is that file as `darkmux_flow::reader` must
//! serve it: one spelling per event, a verdict moved into `payload.verdict`,
//! the mission's whole-run bookend (`dispatch start` / `complete` with
//! `source: "mission"`) as `run.start` / `run.complete`, the unknown action
//! untouched. It was written from the retired-spelling
//! table by hand, not generated by the reader, so it can disagree with the
//! code.

use darkmux_flow::reader::{self, UnknownActions};
use darkmux_flow::FlowAction;
use serde_json::Value;

fn golden(name: &str) -> String {
    let path = format!("{}/../../tests/flow-archive-golden/{name}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{path}: {e}"))
}

#[test]
fn the_archive_reads_exactly_as_its_upgraded_twin() {
    let archive = golden("2026-08-20.jsonl");
    let upgraded = golden("2026-08-20.upgraded.jsonl");
    let read: Vec<Value> = archive.lines().filter_map(reader::parse_value).collect();
    let want: Vec<Value> = upgraded.lines().map(|l| serde_json::from_str(l).unwrap()).collect();
    assert_eq!(read.len(), want.len(), "every line reads, the header included");
    for (i, (got, want)) in read.iter().zip(&want).enumerate() {
        assert_eq!(got, want, "line {}", i + 1);
    }
}

#[test]
fn every_archived_spelling_but_the_one_unknown_reads_as_a_known_action() {
    let archive = golden("2026-08-20.jsonl");
    let mut unknown = UnknownActions::default();
    let mut retired = 0;
    for line in archive.lines() {
        let v: Value = serde_json::from_str(line).unwrap();
        unknown.observe(&v);
        let Some(action) = reader::action_of(&v) else { continue };
        if let FlowAction::Other(u) = &action {
            assert_eq!(u.as_str(), "future.thing", "only the deliberate unknown stays unknown");
        }
        retired += usize::from(matches!(action, FlowAction::Retired(_)));
    }
    assert_eq!(
        retired, 6,
        "telemetry.process, funnel.step, crawl.finding, phase added, mission pause and mission resume read as retired"
    );
    assert_eq!(unknown.total(), 1);
    assert_eq!(unknown.by_name().get("future.thing"), Some(&1));
}

#[test]
fn the_archive_holds_the_spaced_bookends_and_the_upgraded_twin_holds_none() {
    let archive = golden("2026-08-20.jsonl");
    let upgraded = golden("2026-08-20.upgraded.jsonl");
    for spaced in ["\"dispatch start\"", "\"dispatch complete\"", "\"dispatch error\"", "\"step result\"", "\"mission close\""] {
        assert!(archive.contains(spaced), "the archive must exercise {spaced}");
        assert!(!upgraded.contains(spaced), "the upgraded twin must not carry {spaced}");
    }
}

#[test]
fn the_typed_read_agrees_with_the_json_read_on_every_record() {
    let archive = golden("2026-08-20.jsonl");
    let (mut compared, mut headers) = (0, 0);
    for line in archive.lines() {
        let json = reader::parse_value(line).unwrap();
        if json.get("_type").and_then(Value::as_str) == Some("schema") {
            // The header is the one line that is not a record.
            assert!(reader::parse_record(line).is_none(), "the schema header is not a record: {line}");
            headers += 1;
            continue;
        }
        let typed = reader::parse_record(line).unwrap_or_else(|| panic!("a record line failed the typed read: {line}"));
        assert_eq!(json["action"], typed.action.as_str(), "{line}");
        let typed_json = typed.payload.as_ref().map(|p| serde_json::to_value(p).unwrap());
        assert!(payload_agrees(json.get("payload"), typed_json.as_ref()), "{line}");
        compared += 1;
    }
    assert_eq!((headers, compared), (1, 47), "the golden is one header plus 47 records, every one compared");
}

/// The typed payload agrees with the JSON one: every key it carries has the
/// JSON's value. A typed payload drops a key its type does not name and
/// writes `null` for an optional key the archive lacked, so it may hold less
/// than the JSON, never a different value.
fn payload_agrees(json: Option<&serde_json::Value>, typed: Option<&serde_json::Value>) -> bool {
    match (json, typed) {
        (None, None) => true,
        (Some(j), Some(t)) => value_agrees(j, t),
        _ => false,
    }
}

fn value_agrees(json: &serde_json::Value, typed: &serde_json::Value) -> bool {
    use serde_json::Value;
    match (json, typed) {
        (Value::Object(j), Value::Object(t)) => t.iter().all(|(k, tv)| match j.get(k) {
            Some(jv) => value_agrees(jv, tv),
            None => tv.is_null(),
        }),
        (j, t) => j == t,
    }
}

